js/adapt-contrib-trickle.js
less/trickle.less

This PR is to resolve issue https://github.com/adaptlearning/adapt-contrib-trickle/issues/32, it defines a class with padding-bottom rule that is added/removed to the body tag when trickle button is visible/hidden.

Lukasz Grela - trickle auto padding

---

js/adapt-contrib-trickle.js
less/trickle.less

This PR is to resolve issue [adapt-contrib-trickle/issues/32](https://github.com/adaptlearning/adapt-contrib-trickle/issues/32), it defines a class with padding-bottom rule taht is added/removed to the body tag when trickle button is visible/hidden.

Trickle with auto-padding

---

js/adapt-contrib-trickle.js
js/trickle-buttonView.js

Allows other extensions to remove trickle from the page. Useful for testing etc.

Added trickle:kill event

---

bower.json
js/lib/jquery.resize.js

a resize event is triggered on the first click, this fixes that call.

hotfix/resize: stop resize call without resize

---

js/handlers/buttonView.js

https://github.com/adaptlearning/adapt_framework/issues/1591
* android throttles setTimeout, have removed debounce here along with switching inview to requestAnimationFrame
if testing please include inview from https://github.com/adaptlearning/adapt_framework/pull/1595

issue/1591: stop debouncing onscreen handling

---

README.md
example.json
properties.schema

[#1220](https://github.com/adaptlearning/adapt_framework/issues/1220)
* Change _button._autoHide default to false to ensure best accessibility by default
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.

accessibility: issue/1220 Change _button._autoHide default to false

---

js/adapt-contrib-trickle.js

[#2077](https://github.com/adaptlearning/adapt_framework/issues/2077)
* Make trickle focus on the next readable element after the trickle button when autoscroll is off
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.

accessibility: issue/2077 Trickle will focus with autoScroll: false

---

js/handlers/resize.js

[#2236](https://github.com/adaptlearning/adapt_framework/issues/2236)
Force window to scroll if screen reader scrolls #wrapper when step locking
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.

accessibility: fixes 2236 #wrapper scrolls when trickle on screen reader

---

properties.schema

as this creates a poor experience for authoring tool users
also amend `_scrollDuration` default to remove quotes - value is a Number not String

reverts change to make trickle enabled by default on all blocks

---

js/handlers/resize.js

[#2423](https://github.com/adaptlearning/adapt_framework/issues/2423)
* Switched from asynchronous debounced height recalculations to synchronous ones.

issue/2423: remove resize debounce for synchronous height calculations

---

js/adapt-contrib-trickle.js

[#2518](https://github.com/adaptlearning/adapt_framework/issues/2518)
* Focus on next component immediately after button click and before scroll

issue/2518 Focus before scroll

---

js/handlers/buttonView.js

[#2512](https://github.com/adaptlearning/adapt_framework/issues/2520)
* Stopped erroring on no `document.activeElement`

issue/2512 document.activeElement guard

---

less/trickle.less

[#2519](https://github.com/adaptlearning/adapt_framework/issues/2519)
* Prevent wrapper scrolling on ie11
Reference https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-scroll-limit-y-max

issue/2519 stop #wrapper scrolling with trickle active

---

less/trickle-button.less
templates/trickle-button.hbs

- btn type selector applied dynamically
- button width removed from generic btn selector and attached to 'is-full-width' instead
- margin applied to center button by default
Fixes [#2657](https://github.com/adaptlearning/adapt_framework/issues/2657)

FW issue #2657: trickle btn type selector applied dynamically

---

README.md
bower.json
example.json
js/adapt-contrib-trickle.js

fixes https://github.com/adaptlearning/adapt_framework/issues/2813
also:
* return early if neither auto scroll nor trickle button enabled
* update to new a11y API
* double quotes > single
* bump version

don't set focus when there's no trickle button

---

README.md
example.json
js/TrickleButtonModel.js
js/TrickleButtonView.js
js/controller.js
js/models.js

fixes https://github.com/adaptlearning/adapt_framework/issues/3186
fixes https://github.com/adaptlearning/adapt_framework/issues/2623
* Logging prints a full map of the trickle state of the course/page, indented to show structure (only when in debug logging state `?loglevel=debug` + verbose in chrome debugger)
* Locking is now `_isAvailable` aware
* Locking is now also applied when a model is added or removed or its `_isAvailable` is changed
* Fixed some linting issues
* When an article has trickle enabled but `_onChildren: false` and the block has no config, the block now no longer inherits the article config
* Added `_showEndOfPage` to `example.json` and readme
* When article `_requireCompletionOf === Infinity` do not consider the article complete as more blocks will be added (branching …

issue/3186 General bugs and enhancements

---

js/models.js

fixes https://github.com/adaptlearning/adapt_framework/issues/3205
* Article `_onChildren` should default to `true` throughout

issue/3205 Ensure articles without onChildren are onChildren: true

---

js/TrickleButtonModel.js

fixes #126 
* when trickle model is created it now checks to see if it should be complete or not
* check to see if the parent article/block is complete

issue/126 Fixed completion restore on new session

---

js/controller.js

fixes #129 
* Pushed trickle button creation and locking initialization to the final point in the startup process after `app:dataReady` (after spoor restoration), branching and assessment and before `adapt:start`

issue/129 Part fix for branching conflict

---

js/TrickleButtonModel.js
js/TrickleButtonView.js

fixes #134 
* Button view can only be clicked once
* Renamed variable to `isAwaitingPopupClose` for better clarity

issue/134 Fixed visibility for in situ reset

---

js/controller.js
js/models.js

fixes #139 
* Locking is applied asynchronously where multiple assessment are reset outside of a page refresh and after questions are reset or submitted.

issue/139 Asynchronously apply locking where possible

---

js/TrickleButtonModel.js

fixes #141 
* aria-label wasn't hiding when the button was generally disabled as the more specific isButtonDisabled button state property wasn't flipping around correctly
https://github.com/adaptlearning/adapt-contrib-trickle/blob/e1944725ac8014ff04656b47ac708a68a994437f/js/TrickleButtonView.js#L123-L130

issue/141 Vary isButtonDisabled to ensure correct aria-label visibility

---

bower.json
js/TrickleButtonView.js
js/controller.js
js/models.js
js/trickleButton.js

requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Switched to `components.register` from `Adapt.register`
* Use `a11y`, `wait` and `router` directly

issue/2799 Remove redundant behaviour

---

js/models.js

fixes #150 
* Children block locks are not modified if the article has a `_lockType` specified

issue/150 Do not lock children blocks with custom locking

---

js/models.js

fixes #148 
* Check if a block is misconfigured before returning its config

issue/148 Defensive code for mis-configuration of blocks on onChildren: false article

---

js/TrickleButtonModel.js
js/models.js

#155 
* Reset on revisit applies to the button only after its completed according to the various steplocked/completion required criteria. Switched from using `isStepLocked` to `isFinished` which includes `_isCompletionRequired: false` calculations.
* Moved `isLocked` behaviour from `applyLocks` into its own function and added `_isCompletionRequired: false` calculations to check for the button completion instead.

issue/155 Fixed _isCompletionRequired: false

---

templates/trickle-button.hbs

fixes #156 
Divs are not allowed inside buttons.
* Changed button children from div to span

issue/156 Changed divs to spans

---

less/trickle-button.less

fixes https://github.com/adaptlearning/adapt-contrib-trickle/issues/170
* Added `position: relative;` to `trickle__btn` to resolve conflict between newly introduced Vanilla background div and Trickle. Trickle button was unable to be selected if Trickle's `_isFullWidth` was set to `false` due to z-index issue.

Fix: Add position: relative; to trickle btn (fixes #170)

---

js/controller.js

fixes #172
* Trickle will error gracefully when it cannot find an id to scroll to

Fix: Scroll to nowhere (fixes 172)

---

less/trickle-button.less
package.json

fixes https://github.com/adaptlearning/adapt-contrib-core/issues/165
* Styling to move trickle button up on full width with bottom navigation bars
requires https://github.com/adaptlearning/adapt-contrib-core/pull/166

New: Added bottom navigation styling

---

js/models.js

Fixes #180.
If we don't wish to amend `getModelContainer` in this way, the error can be resolved by amending https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/TrickleButtonModel.js#L103 as follows:
``` Javascript
const isParentFinished = (trickleParent?.get('_requireCompletionOf') !== Number.POSITIVE_INFINITY) ?? true;
```

Fix: Amended `getModelContainer` to work with blocks

---

README.md
example.json

Fixes #190 
The ability to disable Trickle globally was already in _config.json_ (not _course.json_) as of release 6.2.0. Therefore, only the documentation and example.json needed to be updated.
* README.md - Change `course.json` references to `config.json`
* README.md - Add line breaks
* example.json - Add example of disabling globally

Fix: Update readme and example (fixes #190)

---

README.md
less/trickle-button.less

Fixes #187
* Replaces `@navigation-height` with `--adapt-navigation-height` CSS variable
1. In _course.json_, set `_navigation._navigationAlignment` to 'bottom'
2. Enable Trickle on some blocks
3. Ensure Navigation and/or Trickle aren't overlapping each other
**Core** - Navigation Button API
https://github.com/adaptlearning/adapt-contrib-core/pull/339

Breaking: Replace @navigation-height with --adapt-navigation-height (fixes #187)

---

bower.json
js/controller.js
js/models.js
package.json

Fixes #196.
* Wait for models state to be restored before adding trickle, to resolve issues with models incorrectly unlocking/relocking across sessions, depending on page structure and trickle config.
* https://github.com/adaptlearning/adapt-contrib-core/pull/413

Fix: restoration issues across sessions or when switching languages

---

js/TrickleButtonView.js
templates/trickle-button.hbs

Relates to Core issue to [allow for locked and inactive disabled buttons to be visually different](https://github.com/adaptlearning/adapt-contrib-core/issues/485). Depending on the button context, the appropriate `.is-locked` or `.is-disabled` classes should be used.
`.is-locked` - applies to buttons that are temporarily disabled due to step locked content.
`.is-disabled` - applies to buttons with functionality not available.
There are no specific Trickle button styles currently. Colours inherit from Vanilla `.btn-text` and `.btn-icon` classes instead which already include [.is-locked](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/1354de838956523d0463dcf7ee409b9b6261f7dd/less/core/button.less#L40) so no further styling required.
`.btn-text` and `.btn-icon` locked states …

New: 'is-locked' btn class added

---

js/TrickleButtonModel.js

fixes https://github.com/adaptlearning/adapt-contrib-assessment/issues/192
* Use parent children instead of stored siblings as children are modified by assessment randomisation and banking but siblings are not

Fix: Use parent children instead of stored siblings

---

less/trickle-button.less

Fixes https://github.com/adaptlearning/adapt-contrib-trickle/issues/215
Removed redundant styles as `.is-locked` never gets appended to the `.trickle` element. Legacy code which pre dates v5 release.
`.is-locked` is only used for button elements to attach state styles as per [`.trickle__btn`](https://github.com/adaptlearning/adapt-contrib-trickle/blob/f4e75b2e946c4db3a7be4b230958f7538ba31ca0/js/TrickleButtonView.js#L132).

Update: remove legacy locked styling (fixes #215)

---

js/models.js

Fixes #194.
* Implement missing `_logState` condition to control debug logs and prevent logging as default (as per schemas).

Update: implement missing `_logState` condition

---

js/models.js

Fixes #223.
Fixes #164.
* Calculate locking on all descendant models to fix issue with incorrect locking for dynamic children order. First model remains `_isLocked` when content order is randomised.

Fix: calculate locking on all descendant models

---

js/models.js

part of https://github.com/adaptlearning/adapt-contrib-core/issues/584
* Treat _isLocked as a lockable attribute, allowing plugins or core to force _isLocked: true
requires https://github.com/adaptlearning/adapt-contrib-core/pull/585

New: Treat _isLocked as a lockable attribute

---

migrations/v2.js
migrations/v3.js
migrations/v4.js
migrations/v5.js
migrations/v6.js
migrations/v7.js

#235 
* added migration scripts

Update: added migration scripts (fixes #235)
