adaptlearning/adapt-contrib-trickle

- js/adapt-contrib-trickle.js
https://adaptlearning.atlassian.net/browse/ABU-493
> Remove references to locked attributes

- js/lib/jquery.resize.js
ratio change wasn't triggering resize event on wrapper
> bugfix: wrapper resize not triggering

- js/adapt-contrib-trickle.js
inline with:
https://github.com/adaptlearning/adapt_framework/pull/694
> ABU-674: Added _isVisible locking integration

- js/lib/jquery.resize.js
can overwhelm ie8
https://github.com/cgkineo/jquery.resize#1
need to move this library into adaptlearning
> issue/49: debounce resize check

- js/trickle-buttonView.js
For ABU-820. Also see adaptlearning/adapt_framework#750
> Add disable animation config check

- README.md
- example.json
- properties.schema
See https://github.com/adaptlearning/adapt_framework/issues/875
> Add _completionAttribute documentation and schema

- js/lib/jquery.resize.js
https://github.com/adaptlearning/adapt_framework/issues/935
> bugfix/935: expando fix

- js/adapt-contrib-trickle.js
- js/handlers/done.js
https://github.com/adaptlearning/adapt_framework/issues/1094
when trickle has finished resizing, locking, unlocking etc, it'll call trickle:done
> issue-1094: added trickle:done event

- js/lib/jquery.resize.js
Pre resize dimension calculation - respond to resize correctly
> Resize bug fix

- js/handlers/tutor.js
1. capture the id of the steplocked origin
2. when tutor is opened or closed check that the tutor is from the steplocked origin
https://github.com/adaptlearning/adapt_framework/issues/1255
> issue-1225: check tutor origin

- README.md
- bower.json
- example.json
- js/handlers/button.js
- js/handlers/buttonView.js
- js/handlers/completion.js
- js/handlers/done.js
- js/handlers/notify.js
- js/handlers/resize.js
- js/handlers/tutor.js
- js/handlers/visibility.js
- js/pageView.js
- js/trickleView.js
- properties.schema
as per https://github.com/adaptlearning/adapt_framework/issues/1322
> change default for _completionAttribute to _isComplete

- properties.schema
Fixes the issues raised here: https://github.com/adaptlearning/adapt_authoring/issues/1539
> Removed required validator

- libraries/jquery.resize.js
https://github.com/adaptlearning/adapt_framework/issues/1580
https://github.com/adaptlearning/adapt_framework/issues/1591
Changes:
* refactor and moved repo to adapt learning
Bug Fix:
* event detachment fix
* fix android setTimeout throttling
> issue-1580: updated jquery.resize to version 2017-06-19

- js/handlers/completion.js
- js/handlers/tutor.js
- js/handlers/visibility.js
- js/lib/adaptModelExtension.js
- js/pageView.js
Related to https://github.com/adaptlearning/adapt_framework/pull/1607
> Backbone Collection cleanup

- properties.schema
https://github.com/adaptlearning/adapt_framework/issues/1672
Remove quotes from default boolean values
> Fixes #1672

- README.md
- bower.json
https://github.com/adaptlearning/adapt_framework/issues/1704
> Version bump to 2.1.5

- libraries/jquery.resize.js
https://github.com/adaptlearning/adapt_framework/issues/1835
> issue/1835: jquery.resize updated to v2017-11-28

- js/adapt-contrib-trickle.js
- js/trickleView.js
Unexpected bookmarking when trickle enabled.
> Fixed:Issue#2023 bookmarking incorrectly

- templates/trickle-button.hbs
[#2075](https://github.com/adaptlearning/adapt_framework/issues/2075)
* Removed unnecessary role
* Fixed spacing
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
> accessibility: issue/#2075

- example.json
- js/handlers/button.js
in order to match the changes made in #94
> set _autoHide to default to false

- example.json
- js/adapt-contrib-trickle.js
- js/handlers/button.js
- js/handlers/buttonView.js
- js/handlers/completion.js
- js/handlers/done.js
- js/handlers/notify.js
- js/handlers/resize.js
- js/handlers/tutor.js
- js/handlers/visibility.js
- js/pageView.js
- js/trickleView.js
- less/trickle-button.less
- less/trickle.less
- templates/trickle-button.hbs
Trickle converted to use 2 spaces for indentation.
> update to use 2 spaces for indentation

- less/trickle-button.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2611
> Removed btn z-index

- bower.json
- js/adapt-contrib-trickle.js
[#2753](https://github.com/adaptlearning/adapt_framework/issues/2753)
* Removed unnecessary global remove event listener
> issue/2753 Removed unnecessary global remove event listener (v5.5.0)

- js/adapt-contrib-trickle.js
[#2856](https://github.com/adaptlearning/adapt_framework/issues/2856)
* Fixed focus issue backport
> issue/2856 Fixed focus issue backport

- less/trickle-button.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891
> Less tidy up

- bower.json
- js/handlers/buttonView.js
fixes https://github.com/adaptlearning/adapt_framework/issues/3047
> #3047 remove button from DOM before scrollTo

- js/adapt-contrib-trickle.js
https://github.com/adaptlearning/adapt_framework/issues/3106
> issue/3106 - fix scrolling transitions

- example.json
- js/TrickleButtonModel.js
- js/TrickleButtonView.js
- js/controller.js
- js/models.js
- properties.schema
fixes https://github.com/adaptlearning/adapt_framework/issues/3168
* Simplified config derivations and fixed bugs
* Simplified locking and component additions, each model will apply its own config as derived rather than nested loops from ancestors
* Renamed some variables, added some comments
* `_showEndOfPage` so that the final button in the last article can be hidden / shown
* Can now go to next page on end (part fix for https://github.com/adaptlearning/adapt_framework/issues/1568)
> issue/3168: Fixes to config inheritance, added _showEndOfPage

- js/TrickleButtonModel.js
- properties.schema
fixes https://github.com/adaptlearning/adapt_framework/issues/3198
* Allowed configuration on blocks
* Make sure default of `true` applies when missing
> issue/3189 Fix _showEndOfPage config and schema

- js/models.js
fixes https://github.com/adaptlearning/adapt_framework/issues/3204
* `_isTrackable: false` to injected components to tell spoor not to track
> issue/3204 Added _isTrackable:false to injected components

- js/TrickleButtonView.js
fixes https://github.com/adaptlearning/adapt_framework/issues/3210
Think I found a typo but not totally sure?
> Line 62 has a typo tricke:killed to trickle:killed

- js/controller.js
https://github.com/adaptlearning/adapt-contrib-trickle/issues/143
> Fix for language switching

- example.json
- js/TrickleButtonModel.js
- js/TrickleButtonView.js
- js/models.js
- properties.schema
- schema/article.schema.json
- schema/block.schema.json
fixes #152 
* completionAttribute to articles and blocks
> issue/152 Allow completionAttribute on blocks and articles

- js/controller.js
- properties.schema
> issues/160 Adding 'isEnabled' config parameter to Trickle

- js/models.js
fixes #154 
* Allow _isAvailable change to reapply locks
> issue/154 Reapply locks if _isAvailable has changed

- example.json
- js/TrickleButtonModel.js
- js/controller.js
- js/models.js
- properties.schema
- schema/config.schema.json
fixes #174
* Added logging switch
* Do not applyLock when not reset
> Fix: Added logging switch and do not applyLocks on completion reset when not reset (fixes #174)

- js/controller.js
#178 
* added missing logging import
> Fix: Added missing logging import (fixes #178)

- templates/trickle-button.hbs
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Fixes #183   
[//]: # (List appropriate steps for testing if needed)
1. Pull down this PR and examine the structure in the output
[//]: # (Mention any other dependencies)
> Fix: Normalizing template icons (fixes: #183)

- js/controller.js
fixes #203 
* Check if the final article is expecting more children and has incomplete trickle button
> Fix: Allow trickle on final branching article (fixes #203)

- js/TrickleButtonModel.js
- js/TrickleButtonView.js
fixes #210 
* Allow missing parent config
> Fix: Allow missing parent config (fixes #210)

- README.md
Fixes https://github.com/adaptlearning/adapt-contrib-trickle/issues/199
* `_isInheritied` attribute description added to README.
> Update: add "_isInherited" to README (fixes #199)

- js/models.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#221 
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Add trickle button to data collection (fixes #221)
> Fix: Add trickle button to data collection (fixes #221)

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue_template.md
Fixes #234 
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
> Chore: Add support for new issue experience (fixes #234)

- js/controller.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Fixes #240
> Fix: Supplying pluginName on updating menu locking (fixes: #240)
